name: tg_weather
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  teledart: ^0.2.1
  dio: ^4.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

